name: Notification on push RU

on:
  release:
    types: [published]

jobs:
  sending:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: Abbadon999/github-to-discord@main
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_EN }}
        DISCORD_USERNAME: GitHub
        DISCORD_AVATAR: https://cdn.discordapp.com/avatars/267312249067012096/7732451a1f9e207b540561a336d0e392.jpg
        MESSAGE_TITLE: New Version
        MESSAGE_DESCRIPTION: Click on the blue version number above to see Changelog!
        MESSAGE_URL: https://github.com/Abbadon999/TerraBetterQuest-1.12.2/blob/TBQ-Heavy-0.3.0/Changelog_EN.md
        MESSAGE_COLOR: 5814783
